/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package secondgui;

import java.awt.Robot;
import java.awt.event.InputEvent;

/**
 *
 * @author Tomek
 */
public class NewJFrame extends javax.swing.JFrame {
    private boolean isStarted = false;
    private int freq = 10;
    private Thread thread;
    private long licznik = 0;
    private boolean isLeftButtonChoosen = false;

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        buttonGroup1.add(jRadioButtonLeft);
        buttonGroup1.add(jRadioButtonRight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jRadioButtonLeft = new javax.swing.JRadioButton();
        jRadioButtonRight = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klikacz");
        setResizable(false);

        jLabel1.setText("Częstotliwość [s]");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("kliknięć: 0");

        jRadioButtonLeft.setText("Lewy");
        jRadioButtonLeft.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonLeftStateChanged(evt);
            }
        });
        jRadioButtonLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLeftActionPerformed(evt);
            }
        });

        jRadioButtonRight.setSelected(true);
        jRadioButtonRight.setText("Prawy");
        jRadioButtonRight.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonRightStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonRight)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1))
                    .addComponent(jLabel2)
                    .addComponent(jRadioButtonLeft))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonRight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().length() > 0)
        {
            try
            {
                freq = (int)Integer.parseInt(jTextField1.getText());
            }
            catch(Exception e)
            {
                // NumberFormatException bad number format
                freq = 10;
            }
                                    
            if(isStarted)
            {
                jButton1.setText("START");
                licznik = 0;
                jLabel2.setText("kliknięć: 0");
                
                isStarted = false;
                
                if(thread != null)
                {
                    thread.interrupt();
                }               
            }
            else
            {
                if(freq>0)
                {
                    jButton1.setText("STOP");
                    isStarted = true;
                    
                    thread = new Thread(new Runnable() {
                        @Override
                        public void run() {
                            while(true)
                            {
                                try{
                                    Thread.sleep(freq*1000);
                                    Robot robot = new Robot();
                                    //robot.mouseMove(300, 550);
                                    if(isLeftButtonChoosen){                        // left button selected            
                                        robot.mousePress( InputEvent.BUTTON1_MASK); 
                                        robot.mouseRelease(InputEvent.BUTTON1_MASK);  
                                    }else{                                          // right button selected
                                        robot.mousePress( InputEvent.BUTTON3_MASK);
                                        robot.mouseRelease(InputEvent.BUTTON3_MASK);                                      
                                    }
                                    jLabel2.setText("kliknięć: "+(++licznik));
                                }
                                catch(InterruptedException e)
                                {
                                    throw new RuntimeException("Przerwano mi sleep!", e);
                                }
                                catch(Exception e){ 
                                    throw new RuntimeException("Robot się zepsuł", e);
                                }                            
                            }

                        }
                    });
                    thread.start();
                }

            }          
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jRadioButtonLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLeftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLeftActionPerformed

    private void jRadioButtonLeftStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonLeftStateChanged
        if(jRadioButtonLeft.isSelected()){
            isLeftButtonChoosen = true;
        }
        else{
            isLeftButtonChoosen = false;
        }        
    }//GEN-LAST:event_jRadioButtonLeftStateChanged

    private void jRadioButtonRightStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonRightStateChanged
        jRadioButtonLeftStateChanged(evt);
    }//GEN-LAST:event_jRadioButtonRightStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButtonLeft;
    private javax.swing.JRadioButton jRadioButtonRight;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
